HZN-one/flex

src/Components/Atoms/FALink/FALink.interfaces.tsx, src/Components/Atoms/FALink/index.tsx
#538 Atom - FALink  https://app.zenhub.com/workspaces/flick-614155581501e1000f356a5d/issues/hzn-one/flick-web/538
=> add new atom FALink

src/Components/Molecules/FMCard/FMCard.interfaces.tsx, src/Components/Molecules/FMCard/index.tsx, src/Definitions/Theme/Theme.tsx
=> #539/FMCard-Setting

.storybook/preview-head.html, .storybook/preview.js, package-lock.json, package.json, src/Definitions/Theme/Theme.interface.tsx, src/Definitions/Theme/Theme.tsx, tsconfig.json
add more color and embedded theme
...
...
...
...
=> embbeded theme and add more color

src/Components/Molecules/FMTableSkeleton/index.tsx, stories/Components/Molecules/FMTableSkeleton/FMTableSkeleton.stories.tsx
- Need to update the component to match the design by updating skeleton height used in table skeleton
- Check if the component updated match the design
https://app.zenhub.com/workspaces/flick-614155581501e1000f356a5d/issues/hzn-one/tms/207
=> #207 Molekul - FMTableSkeleton

src/Components/Atoms/FAChip/FAChip.interface.tsx, src/Components/Atoms/FAFormControlLabel/FAFormControlLabel.interfaces.tsx, src/Components/Atoms/FAFormControlLabel/index.tsx, src/Components/Atoms/FARadio/FARadio.interface.tsx, src/Components/Atoms/FARadio/index.tsx, src/Components/Atoms/FASwitch/FASwitch.interface.tsx, src/Components/Atoms/FASwitch/index.tsx, src/Components/Atoms/FATextField/Input.interface.tsx, src/Components/Atoms/FATextField/index.tsx, src/Components/Atoms/FATooltip/index.tsx, src/Components/Atoms/Icon/Icon.interface.tsx, src/Components/Atoms/Icon/index.tsx, src/Components/Molecules/FMLabelValue/index.tsx, src/Definitions/Theme/Theme.tsx, stories/Components/Atoms/FAIcon/FAIcon.stories.tsx, stories/Components/Atoms/FARadio/FARadio.stories.tsx, stories/Components/Atoms/FASkeleton/FASkeleton.stories.tsx, stories/Components/Atoms/FASwitch/FASwitch.stories.tsx, stories/Components/Atoms/FATextField/FATextField.stories.tsx, stories/Components/Atoms/FATextFieldSelect/FATextFieldSelect.stories.tsx, stories/Components/Atoms/FATooltip/FATooltip.stories.tsx, stories/Components/Molecules/FMLabelValue/FMLabelValue.stories.tsx, test/Components/Atoms/FATextField/index.spec.tsx
1. FATextfield
2. FATooltip
3. FATextFieldSelect
4. FARadio
5. FASwitch
6. FASkeleton 
1. npm run storybook
2. check component that change
...
=> FATooltip FATextFieldSelect FARadio FASwitch FASkeleton

src/Components/Molecules/FMSearch/FMSearch.interfaces.tsx, src/Components/Molecules/FMSearch/index.tsx, src/Components/Organisms/FOCardWithImage/index.tsx, src/Components/Organisms/FOHeader/index.tsx, src/Definitions/Theme/Theme.tsx, stories/Components/Atoms/FACheckbox/FACheckbox.stories.tsx, stories/Components/Molecules/FMSearch/FMSearch.stories.tsx, stories/Introduction.stories.mdx
- Outlined Input border radius set to 8px
- Search icon adornment to use primary color
- Storybook example
https://app.zenhub.com/workspaces/flick-614155581501e1000f356a5d/issues/hzn-one/tms/206
=> #206 Molekul - FMSearch

package.json, src/Components/Organisms/FOCardWithTextField/index.tsx, stories/Components/Organisms/FOCardWithTextField/FOCardWithTextField.stories.tsx
- Need to update the component to match the design
https://app.zenhub.com/workspaces/flick-614155581501e1000f356a5d/issues/hzn-one/tms/209
N / A
=> #209 Organisms - FOCardWithTextField

src/Definitions/Theme/Theme.tsx
1. Fixing margin normal textfield
2. fixing size label textfield
...
...
...
=> fixing theme_textfield

src/Components/Molecules/FMCard/FMCard.interfaces.tsx, src/Components/Molecules/FMCard/index.tsx
1. add feature expand and collapse in FMCARD
1. go to storybook
2.  set isCollapseAble true
...
Storybook
...
https://user-images.githubusercontent.com/74447557/154467858-385ab87f-24c1-4c00-ab3f-b0998e84c513.mp4
=> Add Feature Expand and collapse in FMCARD

src/Components/Molecules/FMTabsMenu/FMTabsMenu.interface.ts, src/Components/Molecules/FMTabsMenu/index.tsx, src/Components/Molecules/index.tsx, src/Definitions/Theme/Theme.tsx, stories/Components/Molecules/FMTabsMenu/FMTabsMenu.stories.tsx, test/Components/Molecules/FMTabsMenu/FMTabsMenu.test.tsx, test/Components/Molecules/FMTabsMenu/__snapshots__/FMTabsMenu.test.tsx.snap
Add new component `FMTabsMenu`
Check if the component match the design
https://app.zenhub.com/workspaces/flick-614155581501e1000f356a5d/issues/hzn-one/tms/301
N / A
https://user-images.githubusercontent.com/46083126/155138593-929251d5-1a1d-4ef3-9457-dc7583c15fc9.mp4
=> #301 Molekul - FMTabsMenu

src/Definitions/Theme/Theme.tsx
Removing incorrect hover color
Check if the component hover color is correct
https://app.zenhub.com/workspaces/flick-614155581501e1000f356a5d/issues/hzn-one/tms/301
N / A
Video Preview
https://slack-files.com/T02AAK5HK0W-F0348L0V2DR-0e73fabcbe
=> Fix - #301 Molekul - FMTabsMenu

src/Components/Molecules/FMLabelValue/index.tsx
1. Configure FMLabelValue
...
...
...
...
...
=> config FMLabelValue

src/Components/Atoms/FATypography/FATypography.interface.ts, src/Components/Molecules/FMLabelValue/index.tsx
Update FATypograhpy types interface
Check if component still work as expected
N / A
N / A
N / A
=> Enhancement - FATypography to receive component props

src/Components/Molecules/FMLabelValue/FMLabelValue.interface.ts
change fm label value interface
test result as expected
...
...
...
=> change interface fm label value, value to undefined

src/Components/Molecules/FMStepper/FMStepper.interface.ts, src/Components/Molecules/FMStepper/index.tsx, stories/Components/Molecules/FMStepper/FMStepper.stories.tsx
- Adding ability to `FMStepper` steps to be controlled from outside component
- Check if uncontrolled component still work as expected
- Check if controlled component that just created works with no error
N / A
N / A
=> Enhancement - FMStepper

src/Components/Layout/FLAuthentication/FLAuthentication.interface.ts, src/Components/Layout/FLAuthentication/index.tsx, src/Components/Organisms/FOHeader/FOHeader.interface.ts, src/Components/Organisms/FOHeader/index.tsx, src/Definitions/constants.ts, stories/Components/Organisms/FOHeader/FOHeader.stories.tsx, test/Components/Organisms/FOHeader/FOHeader.test.tsx
- Updating `FOHeader` so that the component can receive custom logo
Check if component still work as expected
Related to Customer Login Header
N / A
=> Enhancement - FOHeader

package.json, src/Components/Molecules/FMInputAvatar/FMInputAvatar.interface.ts, src/Components/Molecules/FMInputAvatar/index.tsx, src/Components/Molecules/index.tsx, src/Definitions/Theme/Theme.tsx, src/Definitions/constants.ts, stories/Components/Molecules/FMInputAvatar/FMInputAvatar.stories.tsx, test/Components/Molecules/FMInputAvatar/FMInputAvatar.test.tsx, test/Components/Molecules/FMInputAvatar/__snapshots__/FMInputAvatar.test.tsx.snap, test/Components/Molecules/FMStepper/__snapshots__/FMStepper.test.tsx.snap, test/Components/Molecules/FMTableSkeleton/FMTableSkeleton.test.tsx, test/Components/Molecules/FMTableSkeleton/__snapshots__/FMTableSkeleton.test.tsx.snap, test/Components/Organisms/FOCardWithStepper/__snapshots__/FOCardWithStepper.test.tsx.snap
1. create FMInputAvatar
1. check Component can upload file image
2. check component cant change button text and info text
...
=> #407 fm input avatar

src/Components/Atoms/FAButton/FAButton.interface.ts, src/Components/Atoms/FAButton/index.tsx, src/Components/Layout/FLAuthentication/FLAuthentication.interface.ts, src/Components/Layout/FLAuthentication/index.tsx, src/Components/Layout/FLDefault/FLDefault.interface.ts, src/Definitions/Theme/Theme.tsx, stories/Components/Atoms/FAButton/FAButton.stories.tsx
- Adding `isLoading` props to FAButton
- Check if default button props still work as expected
N / A
N / A
=> Enhancement - FAButton

src/Components/Layout/FLAuthentication/FLAuthentication.interface.ts, src/Components/Layout/FLAuthentication/index.tsx, src/Components/Layout/FLDefault/FLDefault.interface.ts, src/Components/Layout/FLDefault/index.tsx, src/Components/Molecules/FMCard/FMCard.interface.ts, src/Components/Molecules/FMCard/index.tsx, src/Components/Organisms/FOCardWithTextField/FOCardWithTextField.interface.ts, src/Components/Organisms/FOCardWithTextField/index.tsx, src/Components/Organisms/FOHeader/FOHeader.interface.ts, src/Components/Organisms/FOHeader/index.tsx, src/Components/Organisms/FOSideBar/index.tsx, src/Definitions/Theme/Theme.tsx, stories/Components/Layout/FLAuthentication/FLAuthentication.stories.tsx, stories/Components/Molecules/FMCard/FMCard.stories.tsx, stories/Components/Organisms/FOCardWithTextField/FOCardWithTextField.stories.tsx, stories/Components/Organisms/FOHeader/FOHeader.stories.tsx, test/Components/Layout/FLAuthentication/FLAuthentication.test.tsx, test/Components/Layout/FLAuthentication/__snapshots__/FLAuthentication.test.tsx.snap, test/Components/Molecules/FMCard/__snapshots__/FMCard.test.tsx.snap, test/Components/Organisms/FOCardWithStepper/FOCardWithStepper.test.tsx, test/Components/Organisms/FOCardWithTextField/FOCardWithTextField.test.tsx, test/Components/Organisms/FOCardWithTextField/__snapshots__/FOCardWithTextField.test.tsx.snap, test/Components/Organisms/FOHeader/FOHeader.test.tsx
- FMCard enhancement with new props
- FOCardWithTextField enhancement
- Add logo and companyLogoProps in FOHeader
- Fix FOSidebar
run `npm run storybook` in flex
...
=> Enhancement fmcard and layout

src/Components/Organisms/FOCardWithTextField/FOCardWithTextField.interface.ts, src/Components/Organisms/FOCardWithTextField/index.tsx, src/Definitions/Theme/Theme.tsx, stories/Components/Organisms/FOCardWithStepper/FOCardWithStepper.stories.tsx
- Update Card border radius from `12px` to `8px`
- Add `buttonSubmitState` props for `FOCardWithTextField` component
`yarn storybook`
N / A
N / A
N / A
=> Enhancement - FOCardWithTextField

src/Components/Atoms/FATextField/index.tsx, src/Definitions/Theme/Theme.tsx
1. enhance styling textfield for autocomplete
1. check component as expected
...
...
...
=> Enhance textfield for autocomplete

package.json, src/Components/Molecules/FMTabsMenu/index.tsx, src/Components/Organisms/FOCardWithImage/FOCardWithImage.interface.ts, src/Components/Organisms/FOCardWithImage/index.tsx, src/Components/Organisms/FOCardWithTextField/FOCardWithTextField.interface.ts, src/Components/Organisms/FOCardWithTextField/index.tsx, src/Definitions/helpers.ts, src/Definitions/index.ts, src/Types/index.ts, stories/Components/Atoms/FAAvatar/FAAvatar.stories.tsx, stories/Components/Atoms/FAButton/FAButton.stories.tsx, stories/Components/Molecules/FMTabsMenu/FMTabsMenu.stories.tsx, stories/Components/Organisms/FOCardWithImage/FOCardWithImage.stories.tsx, stories/Components/Organisms/FOCardWithStepper/FOCardWithStepper.stories.tsx, stories/Components/Organisms/FOCardWithTextField/FOCardWithTextField.stories.tsx, test/Components/Organisms/FOCardWithImage/FOCardWithImage.test.tsx, yarn.lock
- Updating `FMTabsMenu` background color
- Add `buttonSubmitStyle` props to FOCardWithTextField
- Update `FOCardWithImage` 
- Fix some types issue
yarn storybook
- Check if the component still working as expected with no issue
In use of https://app.zenhub.com/workspaces/flick-614155581501e1000f356a5d/issues/hzn-one/tms/281
N / A
N / A
https://user-images.githubusercontent.com/46083126/157849759-5f9410a9-ef62-402b-b710-30252aefb50b.mp4
=> Enhancement - FMTabsMenu & FOCardWithTextField & FOCardWithImage

src/Components/Molecules/FMBackdropImage/FMBackdropImage.interface.ts, src/Components/Molecules/FMBackdropImage/index.tsx, src/Components/Molecules/index.tsx, src/Components/Organisms/FOCardWithImage/index.tsx, src/Definitions/Theme/Theme.tsx, stories/Components/Molecules/FMBackdropImage/FMBackdropImage.stories.tsx, test/Components/Atoms/BaseInput/__snapshots__/BaseInput.test.tsx.snap, test/Components/Atoms/FAChip/__snapshots__/FAChip.test.tsx.snap, test/Components/Atoms/FATextField/__snapshots__/index.spec.tsx.snap, test/Components/Molecules/FMBackdropImage/FMCard.test.tsx, test/Components/Molecules/FMBackdropImage/__snapshots__/FMCard.test.tsx.snap, test/Components/Molecules/FMSearch/__snapshots__/FMSearch.test.tsx.snap, test/Components/Organisms/FOCardWithStepper/__snapshots__/FOCardWithStepper.test.tsx.snap
1. Create FMBackdropImages
1. check component as expected
...
...
=> #449 molecul fm backdrop image

src/Components/Molecules/FMViewPicture/FMViewPicture.interface.ts, src/Components/Molecules/FMViewPicture/index.tsx, src/Components/Molecules/index.tsx, stories/Components/Molecules/FMViewPicture/FMViewPicture.stories.tsx, test/Components/Molecules/FMViewPicture/FMViewPicture.test.tsx
NEW FMViewPicture
FMViewPicture test
FMViewPicture storybook
...
...
...
...
...
=> Fm view picture

src/Components/Organisms/FOPaperRow/FOPaperRow.interface.ts, src/Components/Organisms/FOPaperRow/index.tsx, src/Components/Organisms/index.tsx, stories/Components/Organisms/FOPaperRow/FOPaperRow.stories.tsx, test/Components/Organisms/FOPaperRow/FOPaperRow.test.tsx, test/Components/Organisms/FOPaperRow/__snapshots__/FOPaperRow.test.tsx.snap
- Adding `FOPaperRow` Component
- Adding `FOPaperRow` Stories
- Adding `FOPaperRow` Test
https://app.zenhub.com/workspaces/flick-614155581501e1000f356a5d/issues/hzn-one/tms/404
N / A
Figma
Result
=> #404 Organisms - FOPaperRow

package.json, src/Components/Atoms/FATextField/FATextField.interface.ts, src/Components/Atoms/FATextField/index.tsx, src/Components/Molecules/FMDateRangePicker/FMDateRangePicker.interface.ts, src/Components/Molecules/FMDateRangePicker/index.tsx, src/Components/Molecules/index.tsx, stories/Components/Molecules/FMDateRangePicker/FMDateRangePicker.stories.tsx, test/Components/Molecules/FMDateRangePicker/FMDateRangePicker.test.tsx, test/Components/Molecules/FMDateRangePicker/__snapshots__/FMDateRangePicker.test.tsx.snap, yarn.lock
- Adding `FMDateRangePicker` component
- Adding `FMDateRangePicker` stories
- Adding `FMDateRangePicker` test
https://app.zenhub.com/workspaces/flick-614155581501e1000f356a5d/issues/hzn-one/tms/406
N / A
=> #406 Molecules - FMDateRangePicker

src/Components/Molecules/FMDateRangePicker/FMDateRangePicker.interface.ts, src/Components/Molecules/FMDateRangePicker/index.tsx, src/Components/Organisms/FOPaperRow/FOPaperRow.interface.ts, src/Components/Organisms/FOPaperRow/index.tsx, src/Definitions/Theme/Theme.tsx, stories/Components/Organisms/FOPaperRow/FOPaperRow.stories.tsx
- Add `isStretch` props to `FOPaperRow`
- Update `FMDateRangePicker` spacing style
`yarn storybook`
Check if the component matches the design 
In the use of List Order UI https://app.zenhub.com/workspaces/flick-614155581501e1000f356a5d/issues/hzn-one/tms/400
`FOPaperRow`
N/A
`FMDateRangePicker`
`FOPaperRow`
`FMDateRangePicker`
=> Enhancement - FOPaperRow & FMDateRangePicker

src/Components/Molecules/FMDatePicker/index.tsx, src/Components/Molecules/FMMapsTextField/FMMapsTextField.interface.ts, src/Components/Molecules/FMMapsTextField/index.tsx, src/Components/Molecules/index.tsx, src/Definitions/Theme/Theme.tsx, src/Definitions/constants.ts, stories/Components/Molecules/FMMapsTextField/FMMapsTextField.stories.tsx, test/Components/Molecules/FMMapsTextField/FMMapsTextField.test.tsx, test/Components/Molecules/FMMapsTextField/__snapshots__/FMMapsTextField.test.tsx.snap
- Adding `FMMapsTextField` component
- Adding `FMMapsTextField` story
- Adding `FMMapsTextField` test
`yarn storybook`
Check if the component matches the design
https://app.zenhub.com/workspaces/flick-614155581501e1000f356a5d/issues/hzn-one/tms/559
N / A
=> #559 Molecules - FMMapsTextField

src/Components/Organisms/FODialogWithAlert/FODialogWithAlert.interface.ts, src/Components/Organisms/FODialogWithAlert/index.tsx
- `npm run storybook` and choose FODialogWithAlert
...
...
...
=> Enhancement FODialogWithAlert
